extern const char http_get[4];
extern const char http_post[5];
extern const char http_content_length[17];
extern const char http_crnlcrln[5];
extern const char http_index_html[12];
extern const char http_404_html[10];
extern const char http_413_html[10];
extern const char http_referer[9];
extern const char http_header_200[88];
extern const char http_header_404[95];
extern const char http_content_type_plain[29];
extern const char http_content_type_html[28];
extern const char http_content_type_css [27];
extern const char http_content_type_text[28];
extern const char http_content_type_png [26];
extern const char http_content_type_gif [26];
extern const char http_content_type_jpg [27];
extern const char http_content_type_binary[41];
extern const char http_html[6];
extern const char http_shtml[7];
extern const char http_htm[5];
extern const char http_css[5];
extern const char http_png[5];
extern const char http_gif[5];
extern const char http_jpg[5];
extern const char http_text[5];
extern const char http_txt[5];
